import Head from 'next/head'
import MainContent from '../components/HomePage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Accounting app | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContent />
    </>
  )
}
